package com.example.BudgetBook.infrastructure.persistence.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ExpenseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.id
     *
     * @mbg.generated
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.user_id
     *
     * @mbg.generated
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.category_id
     *
     * @mbg.generated
     */
    private Object categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.expense_date
     *
     * @mbg.generated
     */
    private LocalDate expenseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.payment_method
     *
     * @mbg.generated
     */
    private String paymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expenses.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.id
     *
     * @return the value of expenses.id
     *
     * @mbg.generated
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.id
     *
     * @param id the value for expenses.id
     *
     * @mbg.generated
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.user_id
     *
     * @return the value of expenses.user_id
     *
     * @mbg.generated
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.user_id
     *
     * @param userId the value for expenses.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.category_id
     *
     * @return the value of expenses.category_id
     *
     * @mbg.generated
     */
    public Object getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.category_id
     *
     * @param categoryId the value for expenses.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Object categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.amount
     *
     * @return the value of expenses.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.amount
     *
     * @param amount the value for expenses.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.description
     *
     * @return the value of expenses.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.description
     *
     * @param description the value for expenses.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.expense_date
     *
     * @return the value of expenses.expense_date
     *
     * @mbg.generated
     */
    public LocalDate getExpenseDate() {
        return expenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.expense_date
     *
     * @param expenseDate the value for expenses.expense_date
     *
     * @mbg.generated
     */
    public void setExpenseDate(LocalDate expenseDate) {
        this.expenseDate = expenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.payment_method
     *
     * @return the value of expenses.payment_method
     *
     * @mbg.generated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.payment_method
     *
     * @param paymentMethod the value for expenses.payment_method
     *
     * @mbg.generated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.memo
     *
     * @return the value of expenses.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.memo
     *
     * @param memo the value for expenses.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.created_at
     *
     * @return the value of expenses.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.created_at
     *
     * @param createdAt the value for expenses.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expenses.updated_at
     *
     * @return the value of expenses.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expenses.updated_at
     *
     * @param updatedAt the value for expenses.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}