package com.example.BudgetBook.infrastructure.persistence.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class IncomeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.id
     *
     * @mbg.generated
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.user_id
     *
     * @mbg.generated
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.category_id
     *
     * @mbg.generated
     */
    private Object categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.income_date
     *
     * @mbg.generated
     */
    private LocalDate incomeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incomes.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.id
     *
     * @return the value of incomes.id
     *
     * @mbg.generated
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.id
     *
     * @param id the value for incomes.id
     *
     * @mbg.generated
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.user_id
     *
     * @return the value of incomes.user_id
     *
     * @mbg.generated
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.user_id
     *
     * @param userId the value for incomes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.category_id
     *
     * @return the value of incomes.category_id
     *
     * @mbg.generated
     */
    public Object getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.category_id
     *
     * @param categoryId the value for incomes.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Object categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.amount
     *
     * @return the value of incomes.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.amount
     *
     * @param amount the value for incomes.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.description
     *
     * @return the value of incomes.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.description
     *
     * @param description the value for incomes.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.income_date
     *
     * @return the value of incomes.income_date
     *
     * @mbg.generated
     */
    public LocalDate getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.income_date
     *
     * @param incomeDate the value for incomes.income_date
     *
     * @mbg.generated
     */
    public void setIncomeDate(LocalDate incomeDate) {
        this.incomeDate = incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.memo
     *
     * @return the value of incomes.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.memo
     *
     * @param memo the value for incomes.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.created_at
     *
     * @return the value of incomes.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.created_at
     *
     * @param createdAt the value for incomes.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incomes.updated_at
     *
     * @return the value of incomes.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incomes.updated_at
     *
     * @param updatedAt the value for incomes.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}