package com.example.BudgetBook.infrastructure.persistence.entity;

import java.time.LocalDateTime;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password_hash
     *
     * @mbg.generated
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.provider_id
     *
     * @mbg.generated
     */
    private String providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password_hash
     *
     * @return the value of users.password_hash
     *
     * @mbg.generated
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password_hash
     *
     * @param passwordHash the value for users.password_hash
     *
     * @mbg.generated
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash == null ? null : passwordHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.provider
     *
     * @return the value of users.provider
     *
     * @mbg.generated
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.provider
     *
     * @param provider the value for users.provider
     *
     * @mbg.generated
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.provider_id
     *
     * @return the value of users.provider_id
     *
     * @mbg.generated
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.provider_id
     *
     * @param providerId the value for users.provider_id
     *
     * @mbg.generated
     */
    public void setProviderId(String providerId) {
        this.providerId = providerId == null ? null : providerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}