package com.example.BudgetBook.infrastructure.persistence.mapper;

import com.example.BudgetBook.infrastructure.persistence.entity.CategoryEntity;
import com.example.BudgetBook.infrastructure.persistence.entity.CategoryEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    long countByExample(CategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int insert(CategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int insertSelective(CategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    List<CategoryEntity> selectByExample(CategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    CategoryEntity selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CategoryEntity row, @Param("example") CategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CategoryEntity row, @Param("example") CategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryEntity row);
}