package com.example.BudgetBook.infrastructure.persistence.mapper;

import com.example.BudgetBook.infrastructure.persistence.entity.ExpenseEntity;
import com.example.BudgetBook.infrastructure.persistence.entity.ExpenseEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenseEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    long countByExample(ExpenseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int deleteByExample(ExpenseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int insert(ExpenseEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int insertSelective(ExpenseEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    List<ExpenseEntity> selectByExample(ExpenseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    ExpenseEntity selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ExpenseEntity row, @Param("example") ExpenseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ExpenseEntity row, @Param("example") ExpenseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExpenseEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenses
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpenseEntity row);
}