package com.example.BudgetBook.infrastructure.persistence.mapper;

import com.example.BudgetBook.infrastructure.persistence.entity.IncomeEntity;
import com.example.BudgetBook.infrastructure.persistence.entity.IncomeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IncomeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    long countByExample(IncomeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int deleteByExample(IncomeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int insert(IncomeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int insertSelective(IncomeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    List<IncomeEntity> selectByExample(IncomeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    IncomeEntity selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") IncomeEntity row, @Param("example") IncomeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") IncomeEntity row, @Param("example") IncomeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IncomeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incomes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IncomeEntity row);
}